Update channel setting
snu-quiqcl/wlm-server pull request #31
Opened 2024-11-21 03:33 UTC by BECATRUE

This resolves #7.

I implemented the features as below.
- Receive a request to start/stop measurement of a specific channel through `operation/:channel/`.
- Receive a request to update exposure time or period of a specific channel through `setting/:channel/`.

The detailed logic for WLM control can be found in #7.

To test these features, you can mock the `WLM` class. The following code might be helpful.
```python
class WLM:
    def open(self):
        print('WLM is connected.')

    def close(self):
        print('WLM is disconnected.')

    def start_measurement(self):
        print('Measurement is stared.')

    def stop_measurement(self):
        print('Measurement is stopped')

    def set_exposure(self, exposure, channel):
        print(f'Exposure time of channel {channel} is set to {exposure}.')
```

And the example client code is as follows.
```python
import requests

BASE_URL = 'http://localhost:8000'

with requests.Session() as session:
    data = {'username': 'user1', 'password': 'OOOO'}
    response = session.post(BASE_URL + '/user/signin/', json=data)

    csrf_token = session.cookies.get('csrftoken')
    headers = {'X-CSRFToken': csrf_token}

    data = {'exposure': 1}
    response = session.post(BASE_URL + '/setting/1/', json=data, headers=headers)
    
    data = {'period': 1}
    response = session.post(BASE_URL + '/setting/1/', json=data, headers=headers)

    data = {'on': True}
    response = session.post(BASE_URL + '/operation/1/', json=data, headers=headers)
    # open WLM connection and start measurement of channel 1

    data = {'on': True}
    response = session.post(BASE_URL + '/operation/2/', json=data, headers=headers)
    # start measurement of channel 2

    data = {'on': False}
    response = session.post(BASE_URL + '/operation/1/', json=data, headers=headers)
    # stop measurement of channel 1

    data = {'on': False}
    response = session.post(BASE_URL + '/operation/2/', json=data, headers=headers)
    # stop measurement of channel 2 and close WLM connection

    response = session.post(BASE_URL + '/user/signout/', headers=headers)
    print(response.status_code)  # 200
```

P.S. I updated `.pylintrc` file to allow more similar codes like `iquip`.

2024-11-21 08:04 UTC, kangz12345 requested changes

2024-11-21 08:04 UTC, kangz12345 commented on wlm_server/operation/views.py
> +    is_channel_running = any(op.channel.channel == ch and op.on for op in latest_operations)
How about
```python
on_operations = [op for op in latest_operations if op.on]
is_wlm_running = len(on_operations) > 0
is_channel_running = any(op.channel.channel == ch for op in on_operations)
```
as it can reduce iterations?

2024-11-21 08:04 UTC, kangz12345 commented on wlm_server/operation/views.py
> +    print(is_wlm_running, is_channel_running)
Maybe you forgot to remove this line 😄

2024-11-21 08:04 UTC, kangz12345 commented on wlm_server/operation/views.py
> +    channel = Channel.objects.get(channel=ch)
Let's return status 400 (Bad request) if this raises an error (given channel does not exist).

2024-11-21 08:04 UTC, kangz12345 commented on wlm_server/operation/views.py
> +    if user.team not in channel.teams.all():
Maybe we can use [`contains()`](https://docs.djangoproject.com/en/5.1/ref/models/querysets/#contains) to reduce transactions.

2024-11-21 08:04 UTC, kangz12345 commented on wlm_server/operation/views.py
> +    req_data = request.data.copy()
Is there is a reason for the copy?

2024-11-21 08:04 UTC, kangz12345 commented on wlm_server/operation/views.py
> +            task_handler = TaskHandler()
A daemon thread will be killed abruptly when the main process exits. I think we should make it non-daemonic and stop it gracefully when the server stops.
Let's design and implement it in another PR.

2024-11-21 08:04 UTC, kangz12345 commented on wlm_server/operation/views.py
> +            message_queue.push(message)
I guess the `not`'s should be removed.

2024-11-21 11:01 UTC, BECATRUE commented on wlm_server/operation/views.py
> +    is_channel_running = any(op.channel.channel == ch and op.on for op in latest_operations)
As we discussed offline, we decided to leave it as it is since there likely won't be a significant difference.

2024-11-21 11:01 UTC, BECATRUE commented on wlm_server/operation/views.py
> +            message_queue.push(message)
As we discussed, using `not` looks correct.

2024-11-21 11:13 UTC, BECATRUE commented on wlm_server/operation/views.py
> +    channel = Channel.objects.get(channel=ch)
How about returning status 404 (Not Found)? I find it more proper.

2024-11-21 11:27 UTC, BECATRUE commented on wlm_server/operation/views.py
> +    req_data = request.data.copy()
I just learned it that way in SWPP course😅

However, there seems to be a reason for using `copy()`.
Referred to [blog](https://velog.io/@qlgks1/Django-request-HttpRequest-QueryDict), the `request.data` is immutable, so if we want to modify it directly, we should deep-copy it.
In this case, we don't have to consider the mutability issue, but how about keep it as it is for generality?

2024-11-21 12:44 UTC, kangz12345 commented on wlm_server/operation/views.py
> +    channel = Channel.objects.get(channel=ch)
I agree with you, let's return 404!

2024-11-21 12:44 UTC, kangz12345 commented on wlm_server/operation/views.py
> +    req_data = request.data.copy()
Alright, then let's use `copy()` for `request.data`.

2024-11-22 02:40 UTC, kangz12345 requested changes

2024-11-22 02:40 UTC, kangz12345 commented on wlm_server/setting/views.py
>      if user.team not in channel.teams.all():
Let's use `contains()` here as well!

2024-11-22 03:09 UTC, kangz12345 approved these changes
LGTM

2024-11-22 03:11 UTC, merged